### PR TITLE
Create dependencies.md [ci skip]

### PR DESCRIPTION
**Pull request by gcolliso**

### CODE REVIEW

**Comment by derekcollison** [comment]
Could you update this to most current versions?

**Review by derekcollison — APPROVED** [review]
LGTM

**Review by derekcollison — COMMENTED** [review]
These are not for this library. They are for the TS/JS one.

**Comment by gcolliso** [comment]
So as these are the same as the previous in 2021, you're saying the file from 2021 was incorrect?

**Comment by derekcollison** [comment]
No but would squash the two commits since the first was wrong.

**Pull request closed without merging**
